import type { TeamDefinition } from "../types";

export const GLEAGUE_TEAMS: TeamDefinition[] = [
	{
		name: "Spurs",
		city: "Austin",
		fullName: "Austin Spurs",
		abbreviation: "AUS",
		logoSlug: "aus",
		colors: {
			brand: { primary: "C4CED4", secondary: "000000" },
			display: { dark: "C4CED4", light: "000000" },
		},
		social: { twitter: "austinspurs", instagram: "austinspurs" },
		api: { id: "2", slug: "aus" },
		statsApi: { id: "1612709890", slug: "spurs" },
	},
	{
		name: "Squadron",
		city: "Birmingham",
		fullName: "Birmingham Squadron",
		abbreviation: "BIR",
		logoSlug: "bir",
		colors: {
			brand: { primary: "002A5C", secondary: "B4975A" },
			display: { dark: "B4975A", light: "002A5C" },
		},
		social: { twitter: "babornsquadron", instagram: "bhamsquadron" },
		api: { id: "6", slug: "bir" },
		statsApi: { id: "1612709913", slug: "squadron" },
	},
	{
		name: "Go-Go",
		city: "Capital City",
		fullName: "Capital City Go-Go",
		abbreviation: "CAP",
		logoSlug: "cap",
		colors: {
			brand: { primary: "002B5C", secondary: "E31837" },
			display: { dark: "E31837", light: "002B5C" },
		},
		social: { twitter: "capitalcitygogo", instagram: "capitalcitygogo" },
		api: { id: "4", slug: "cap" },
		statsApi: { id: "1612709928", slug: "go-go" },
	},
	{
		name: "Charge",
		city: "Cleveland",
		fullName: "Cleveland Charge",
		abbreviation: "CLC",
		logoSlug: "clc",
		colors: {
			brand: { primary: "061642", secondary: "FDBB30" },
			display: { dark: "FDBB30", light: "061642" },
		},
		social: { twitter: "clevelandcharge", instagram: "clevelandcharge" },
		api: { id: "3", slug: "clc" },
		statsApi: { id: "1612709893", slug: "charge" },
	},
	{
		name: "Skyhawks",
		city: "College Park",
		fullName: "College Park Skyhawks",
		abbreviation: "CPS",
		logoSlug: "cps",
		colors: {
			brand: { primary: "000000", secondary: "B3042A" },
			display: { dark: "B3042A", light: "000000" },
		},
		social: { twitter: "cpskyhawks", instagram: "cpskyhawks" },
		api: { id: "28", slug: "cps" },
		statsApi: { id: "1612709929", slug: "skyhawks" },
	},
	{
		name: "Blue Coats",
		city: "Delaware",
		fullName: "Delaware Blue Coats",
		abbreviation: "DEL",
		logoSlug: "del",
		colors: {
			brand: { primary: "003DA6", secondary: "DD0031" },
			display: { dark: "DD0031", light: "003DA6" },
		},
		social: { twitter: "delowarebluecoats", instagram: "bluecoats" },
		api: { id: "5", slug: "del" },
		statsApi: { id: "1612709909", slug: "blue-coats" },
	},
	{
		name: "Gold",
		city: "Grand Rapids",
		fullName: "Grand Rapids Gold",
		abbreviation: "GRD",
		logoSlug: "grd",
		colors: {
			brand: { primary: "C8102E", secondary: "1D428A" },
			display: { dark: "C8102E", light: "1D428A" },
		},
		social: { twitter: "gaborngold", instagram: "grandrapidsgold" },
		api: { id: "8", slug: "grd" },
		statsApi: { id: "1612709917", slug: "gold" },
	},
	{
		name: "Swarm",
		city: "Greensboro",
		fullName: "Greensboro Swarm",
		abbreviation: "GBO",
		logoSlug: "gbo",
		colors: {
			brand: { primary: "007BBC", secondary: "1D1160" },
			display: { dark: "007BBC", light: "1D1160" },
		},
		social: { twitter: "gabornoswarm", instagram: "greensboroswarm" },
		api: { id: "9", slug: "gbo" },
		statsApi: { id: "1612709922", slug: "swarm" },
	},
	{
		name: "Wolves",
		city: "Iowa",
		fullName: "Iowa Wolves",
		abbreviation: "IWA",
		logoSlug: "iwa",
		colors: {
			brand: { primary: "0C2340", secondary: "236192" },
			display: { dark: "236192", light: "0C2340" },
		},
		social: { twitter: "iabornoawolves", instagram: "iowawolves" },
		api: { id: "10", slug: "iwa" },
		statsApi: { id: "1612709911", slug: "wolves" },
	},
	{
		name: "Nets",
		city: "Long Island",
		fullName: "Long Island Nets",
		abbreviation: "LIN",
		logoSlug: "lin",
		colors: {
			brand: { primary: "006BB6", secondary: "ED174C" },
			display: { dark: "ED174C", light: "006BB6" },
		},
		social: { twitter: "longislandnets", instagram: "longislandnets" },
		api: { id: "12", slug: "lin" },
		statsApi: { id: "1612709921", slug: "nets" },
	},
	{
		name: "Celtics",
		city: "Maine",
		fullName: "Maine Celtics",
		abbreviation: "MNE",
		logoSlug: "mne",
		colors: {
			brand: { primary: "006532", secondary: "F1F2F3" },
			display: { dark: "F1F2F3", light: "006532" },
		},
		social: { twitter: "maineceltics", instagram: "maineceltics" },
		api: { id: "13", slug: "mne" },
		statsApi: { id: "1612709915", slug: "celtics" },
	},
	{
		name: "Hustle",
		city: "Memphis",
		fullName: "Memphis Hustle",
		abbreviation: "MHU",
		logoSlug: "mhu",
		colors: {
			brand: { primary: "E2231A", secondary: "717271" },
			display: { dark: "E2231A", light: "717271" },
		},
		social: { twitter: "memphishustle", instagram: "memphishustle" },
		api: { id: "14", slug: "mhu" },
		statsApi: { id: "1612709926", slug: "hustle" },
	},
	{
		name: "Capitanes",
		city: "Mexico City",
		fullName: "Mexico City Capitanes",
		abbreviation: "MXC",
		logoSlug: "mxc",
		colors: {
			brand: { primary: "3A4C98", secondary: "FFFFFF" },
			display: { dark: "FFFFFF", light: "3A4C98" },
		},
		social: { twitter: "cabornoitanes", instagram: "capitanesmx" },
		api: { id: "124612", slug: "mxc" },
		statsApi: { id: "1612709931", slug: "capitanes" },
	},
	{
		name: "Cruise",
		city: "Motor City",
		fullName: "Motor City Cruise",
		abbreviation: "MCC",
		logoSlug: "mcc",
		colors: {
			brand: { primary: "FA002C", secondary: "006BB6" },
			display: { dark: "FA002C", light: "006BB6" },
		},
		social: { twitter: "motorcitycruise", instagram: "motorcitycruise" },
		api: { id: "15", slug: "mcc" },
		statsApi: { id: "1612709932", slug: "cruise" },
	},
	{
		name: "Boom",
		city: "Noblesville",
		fullName: "Noblesville Boom",
		abbreviation: "NOB",
		logoSlug: "nob",
		colors: {
			brand: { primary: "002D62", secondary: "FDBB30" },
			display: { dark: "FDBB30", light: "002D62" },
		},
		social: { twitter: "noblesvilleboom", instagram: "noblesvilleboom" },
		api: { id: "7", slug: "nob" },
		statsApi: { id: "1612709910", slug: "boom" },
	},
	{
		name: "Blue",
		city: "Oklahoma City",
		fullName: "Oklahoma City Blue",
		abbreviation: "OKL",
		logoSlug: "okl",
		colors: {
			brand: { primary: "007AC1", secondary: "EF3B24" },
			display: { dark: "EF3B24", light: "007AC1" },
		},
		social: { twitter: "oabornokcblue", instagram: "okcblue" },
		api: { id: "16", slug: "okl" },
		statsApi: { id: "1612709889", slug: "blue" },
	},
	{
		name: "Magic",
		city: "Osceola",
		fullName: "Osceola Magic",
		abbreviation: "OSC",
		logoSlug: "osc",
		colors: {
			brand: { primary: "0077C0", secondary: "000000" },
			display: { dark: "0077C0", light: "0077C0" },
		},
		social: { twitter: "osceolamagic", instagram: "osceolamagic" },
		api: { id: "11", slug: "osc" },
		statsApi: { id: "1612709925", slug: "magic" },
	},
	{
		name: "905",
		city: "Raptors",
		fullName: "Raptors 905",
		abbreviation: "RAP",
		logoSlug: "rap",
		colors: {
			brand: { primary: "CE1141", secondary: "000000" },
			display: { dark: "CE1141", light: "000000" },
		},
		social: { twitter: "rabornotors905", instagram: "raptors905" },
		api: { id: "17", slug: "rap" },
		statsApi: { id: "1612709920", slug: "905" },
	},
	{
		name: "Vipers",
		city: "Rio Grande Valley",
		fullName: "Rio Grande Valley Vipers",
		abbreviation: "RGV",
		logoSlug: "rgv",
		colors: {
			brand: { primary: "CE1141", secondary: "BEC0C2" },
			display: { dark: "CE1141", light: "BEC0C2" },
		},
		social: { twitter: "rgvipers", instagram: "rgvipers" },
		api: { id: "18", slug: "rgv" },
		statsApi: { id: "1612709908", slug: "vipers" },
	},
	{
		name: "Remix",
		city: "Rip City",
		fullName: "Rip City Remix",
		abbreviation: "RCY",
		logoSlug: "rcity",
		colors: {
			brand: { primary: "E03A3E", secondary: "000000" },
			display: { dark: "E03A3E", light: "000000" },
		},
		social: { twitter: "ripcityremix", instagram: "ripcityremix" },
		api: { id: "128019", slug: "rcity" },
		statsApi: { id: "1612709933", slug: "remix" },
	},
	{
		name: "Stars",
		city: "Salt Lake City",
		fullName: "Salt Lake City Stars",
		abbreviation: "SLC",
		logoSlug: "slc",
		colors: {
			brand: { primary: "002B5C", secondary: "F9A01B" },
			display: { dark: "F9A01B", light: "002B5C" },
		},
		social: { twitter: "slcstars", instagram: "slcstars" },
		api: { id: "19", slug: "slc" },
		statsApi: { id: "1612709903", slug: "stars" },
	},
	{
		name: "Clippers",
		city: "San Diego",
		fullName: "San Diego Clippers",
		abbreviation: "SAN",
		logoSlug: "san",
		colors: {
			brand: { primary: "C8102E", secondary: "1D428A" },
			display: { dark: "C8102E", light: "1D428A" },
		},
		social: { twitter: "saborondiegoclippers", instagram: "sandiegoclippers" },
		api: { id: "1", slug: "san" },
		statsApi: { id: "1612709924", slug: "clippers" },
	},
	{
		name: "Warriors",
		city: "Santa Cruz",
		fullName: "Santa Cruz Warriors",
		abbreviation: "SCW",
		logoSlug: "scw",
		colors: {
			brand: { primary: "006BB6", secondary: "FDB927" },
			display: { dark: "FDB927", light: "006BB6" },
		},
		social: { twitter: "saboroncruzwarriors", instagram: "santacruzwarriors" },
		api: { id: "20", slug: "scw" },
		statsApi: { id: "1612709902", slug: "warriors" },
	},
	{
		name: "Skyforce",
		city: "Sioux Falls",
		fullName: "Sioux Falls Skyforce",
		abbreviation: "SXF",
		logoSlug: "sxf",
		colors: {
			brand: { primary: "98002E", secondary: "000000" },
			display: { dark: "98002E", light: "98002E" },
		},
		social: { twitter: "sfskabornoforce", instagram: "sabornokyforce" },
		api: { id: "21", slug: "sxf" },
		statsApi: { id: "1612709904", slug: "skyforce" },
	},
	{
		name: "Lakers",
		city: "South Bay",
		fullName: "South Bay Lakers",
		abbreviation: "SBL",
		logoSlug: "sbl",
		colors: {
			brand: { primary: "552583", secondary: "FDB927" },
			display: { dark: "FDB927", light: "552583" },
		},
		social: { twitter: "southbaylakers", instagram: "southbaylakers" },
		api: { id: "22", slug: "sbl" },
		statsApi: { id: "1612709905", slug: "lakers" },
	},
	{
		name: "Kings",
		city: "Stockton",
		fullName: "Stockton Kings",
		abbreviation: "STO",
		logoSlug: "sto",
		colors: {
			brand: { primary: "5A2D81", secondary: "000000" },
			display: { dark: "5A2D81", light: "000000" },
		},
		social: { twitter: "stocktonkings", instagram: "stocktonkings" },
		api: { id: "23", slug: "sto" },
		statsApi: { id: "1612709914", slug: "kings" },
	},
	{
		name: "Legends",
		city: "Texas",
		fullName: "Texas Legends",
		abbreviation: "TEX",
		logoSlug: "tex",
		colors: {
			brand: { primary: "0053BC", secondary: "00285E" },
			display: { dark: "0053BC", light: "00285E" },
		},
		social: { twitter: "texlegends", instagram: "texlegends" },
		api: { id: "24", slug: "tex" },
		statsApi: { id: "1612709918", slug: "legends" },
	},
	{
		name: "Suns",
		city: "Valley",
		fullName: "Valley Suns",
		abbreviation: "VAL",
		logoSlug: "valley",
		colors: {
			brand: { primary: "E56020", secondary: "1D1160" },
			display: { dark: "E56020", light: "1D1160" },
		},
		social: { twitter: "valleysuns", instagram: "valleyphxsuns" },
		api: { id: "129713", slug: "valley" },
		statsApi: { id: "1612709934", slug: "suns" },
	},
	{
		name: "Knicks",
		city: "Westchester",
		fullName: "Westchester Knicks",
		abbreviation: "WES",
		logoSlug: "wes",
		colors: {
			brand: { primary: "006BB6", secondary: "F58426" },
			display: { dark: "F58426", light: "006BB6" },
		},
		social: { twitter: "westaboronicks", instagram: "westchesterknicks" },
		api: { id: "25", slug: "wes" },
		statsApi: { id: "1612709919", slug: "knicks" },
	},
	{
		name: "Bulls",
		city: "Windy City",
		fullName: "Windy City Bulls",
		abbreviation: "WCB",
		logoSlug: "wcb",
		colors: {
			brand: { primary: "CE1141", secondary: "000000" },
			display: { dark: "CE1141", light: "000000" },
		},
		social: { twitter: "windycitybulls", instagram: "windycitybulls" },
		api: { id: "26", slug: "wcb" },
		statsApi: { id: "1612709923", slug: "bulls" },
	},
	{
		name: "Herd",
		city: "Wisconsin",
		fullName: "Wisconsin Herd",
		abbreviation: "WIS",
		logoSlug: "wis",
		colors: {
			brand: { primary: "00471B", secondary: "EEE1C6" },
			display: { dark: "EEE1C6", light: "00471B" },
		},
		social: { twitter: "wisconsinherd", instagram: "wisconsinherd" },
		api: { id: "27", slug: "wis" },
		statsApi: { id: "1612709927", slug: "herd" },
	},
];
