import type { TeamDefinition } from "../types";

export const WNBA_TEAMS: TeamDefinition[] = [
	{
		name: "Dream",
		city: "Atlanta",
		fullName: "Atlanta Dream",
		abbreviation: "ATL",
		logoSlug: "atl",
		colors: {
			brand: { primary: "E31837", secondary: "5091CC" },
			display: { dark: "E31837", light: "5091CC" },
		},
		api: { id: "20", slug: "atl" },
	},
	{
		name: "Sky",
		city: "Chicago",
		fullName: "Chicago Sky",
		abbreviation: "CHI",
		logoSlug: "chi",
		colors: {
			brand: { primary: "5091CD", secondary: "FFD520" },
			display: { dark: "5091CD", light: "FFD520" },
		},
		api: { id: "19", slug: "chi" },
	},
	{
		name: "Sun",
		city: "Connecticut",
		fullName: "Connecticut Sun",
		abbreviation: "CON",
		logoSlug: "conn",
		colors: {
			brand: { primary: "F05023", secondary: "0A2240" },
			display: { dark: "F05023", light: "0A2240" },
		},
		api: { id: "18", slug: "conn" },
	},
	{
		name: "Wings",
		city: "Dallas",
		fullName: "Dallas Wings",
		abbreviation: "DAL",
		logoSlug: "dal",
		colors: {
			brand: { primary: "002B5C", secondary: "C4D600" },
			display: { dark: "C4D600", light: "002B5C" },
		},
		api: { id: "3", slug: "dal" },
	},
	{
		name: "Valkyries",
		city: "Golden State",
		fullName: "Golden State Valkyries",
		abbreviation: "GSV",
		logoSlug: "gs",
		colors: {
			brand: { primary: "5E2C83", secondary: "F4C01E" },
			display: { dark: "F4C01E", light: "5E2C83" },
		},
		api: { id: "129689", slug: "gs" },
	},
	{
		name: "Fever",
		city: "Indiana",
		fullName: "Indiana Fever",
		abbreviation: "IND",
		logoSlug: "ind",
		colors: {
			brand: { primary: "002D62", secondary: "E03A3E" },
			display: { dark: "E03A3E", light: "002D62" },
		},
		api: { id: "5", slug: "ind" },
	},
	{
		name: "Aces",
		city: "Las Vegas",
		fullName: "Las Vegas Aces",
		abbreviation: "LVA",
		logoSlug: "lv",
		colors: {
			brand: { primary: "000000", secondary: "C4CED4" },
			display: { dark: "C4CED4", light: "000000" },
		},
		api: { id: "17", slug: "lv" },
	},
	{
		name: "Sparks",
		city: "Los Angeles",
		fullName: "Los Angeles Sparks",
		abbreviation: "LAS",
		logoSlug: "la",
		colors: {
			brand: { primary: "552583", secondary: "FDB927" },
			display: { dark: "FDB927", light: "552583" },
		},
		api: { id: "6", slug: "la" },
	},
	{
		name: "Lynx",
		city: "Minnesota",
		fullName: "Minnesota Lynx",
		abbreviation: "MIN",
		logoSlug: "min",
		colors: {
			brand: { primary: "0C2340", secondary: "78BE20" },
			display: { dark: "78BE20", light: "0C2340" },
		},
		api: { id: "8", slug: "min" },
	},
	{
		name: "Liberty",
		city: "New York",
		fullName: "New York Liberty",
		abbreviation: "NYL",
		logoSlug: "ny",
		colors: {
			brand: { primary: "6ECEB2", secondary: "000000" },
			display: { dark: "6ECEB2", light: "000000" },
		},
		api: { id: "9", slug: "ny" },
	},
	{
		name: "Mercury",
		city: "Phoenix",
		fullName: "Phoenix Mercury",
		abbreviation: "PHX",
		logoSlug: "phx",
		colors: {
			brand: { primary: "201747", secondary: "E56020" },
			display: { dark: "E56020", light: "201747" },
		},
		api: { id: "11", slug: "phx" },
	},
	{
		name: "Storm",
		city: "Seattle",
		fullName: "Seattle Storm",
		abbreviation: "SEA",
		logoSlug: "sea",
		colors: {
			brand: { primary: "2C5234", secondary: "FEE11A" },
			display: { dark: "FEE11A", light: "2C5234" },
		},
		api: { id: "14", slug: "sea" },
	},
	{
		name: "Mystics",
		city: "Washington",
		fullName: "Washington Mystics",
		abbreviation: "WAS",
		logoSlug: "wsh",
		colors: {
			brand: { primary: "002B5C", secondary: "E31837" },
			display: { dark: "E31837", light: "002B5C" },
		},
		api: { id: "16", slug: "wsh" },
	},
];
