// @generated by convex-zen generate. DO NOT EDIT.
import { components } from "../../_generated/api";
import { createConvexZenClient } from "convex-zen";
import zenConfig from "../../zen.config";

export const auth = createConvexZenClient(
  components.zenComponent as Record<string, unknown>,
  zenConfig,
  { runtimeKind: "app" }
);
