// @generated by convex-zen generate. DO NOT EDIT.
export const authMeta = {
  "core": {
    "currentUser": "query",
    "exchangeOAuthProxyCode": "action",
    "getOAuthUrl": "mutation",
    "handleOAuthCallback": "action",
    "handleOAuthProxyCallback": "action",
    "invalidateSession": "mutation",
    "requestPasswordReset": "mutation",
    "resetPassword": "mutation",
    "signInWithCredential": "mutation",
    "signUp": "mutation",
    "updateProfile": "mutation",
    "validateSession": "mutation",
    "verifyEmail": "mutation"
  },
  "plugin": {}
} as const;

export const authCoreMeta = authMeta.core;
export const authPluginMeta = authMeta.plugin;

export type AuthMeta = typeof authMeta;
export type AuthCoreMeta = typeof authCoreMeta;
export type AuthPluginMeta = typeof authPluginMeta;
