// @generated by convex-zen generate. DO NOT EDIT.
import zenConfig from "../../zen.config";

function resolveTokenEncryptionSecret(): string | undefined {
  const explicit = zenConfig.runtime?.tokenEncryptionSecret?.trim();
  if (explicit && explicit.length > 0) {
    return explicit;
  }
  const envVar = zenConfig.runtime?.tokenEncryptionSecretEnvVar ?? "CONVEX_ZEN_SECRET";
  const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
  const fromEnv = env?.[envVar]?.trim();
  return fromEnv && fromEnv.length > 0 ? fromEnv : undefined;
}

const oauthProviders = (zenConfig.providers ?? []).map((provider) => {
  if (provider.tokenEncryptionSecret !== undefined) {
    return provider;
  }
  const tokenEncryptionSecret = resolveTokenEncryptionSecret();
  if (!tokenEncryptionSecret) {
    return provider;
  }
  return {
    ...provider,
    tokenEncryptionSecret,
  };
});

export function resolveOAuthProvider(providerId: string) {
  return oauthProviders.find((provider) => provider.id === providerId);
}

export function resolveDefaultRole(): string | undefined {
  for (const plugin of zenConfig.plugins ?? []) {
    const role = plugin.definition.hooks?.onUserCreated?.defaultRole?.(
      plugin.options,
    );
    if (role !== undefined) {
      const trimmed = role.trim();
      return trimmed.length > 0 ? trimmed : undefined;
    }
  }
  return undefined;
}
