// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { action, mutation, query } from "../_generated/server";
import { auth } from "./_generated/auth";

function assertCredentialSignInArgs(args: {
  email?: string;
  username?: string;
  password: string;
  ipAddress?: string;
  userAgent?: string;
}): asserts args is
  | {
      email: string;
      username?: string;
      password: string;
      ipAddress?: string;
      userAgent?: string;
    }
  | {
      username: string;
      email?: string;
      password: string;
      ipAddress?: string;
      userAgent?: string;
    } {
  if (
    (typeof args.email === "string" && args.email.trim().length > 0) ||
    (typeof args.username === "string" && args.username.trim().length > 0)
  ) {
    return;
  }
  throw new Error("Either email or username is required.");
}


export const signUp = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    name: v.optional(v.string()),
    username: v.string(),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.signUp(ctx, args);
  },
});

export const signInWithCredential = mutation({
  args: {
    email: v.optional(v.string()),
    username: v.optional(v.string()),
    password: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    assertCredentialSignInArgs(args);
    return auth.signIn(ctx, args);
  },
});

export const verifyEmail = mutation({
  args: {
    email: v.string(),
    code: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.verifyEmail(ctx, args);
  },
});

export const requestPasswordReset = mutation({
  args: {
    email: v.string(),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.requestPasswordReset(ctx, args);
  },
});

export const resetPassword = mutation({
  args: {
    email: v.string(),
    code: v.string(),
    newPassword: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.resetPassword(ctx, args);
  },
});

export const invalidateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    await auth.signOut(ctx, args.token);
  },
});

export const validateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.session.validate(ctx, args.token);
  },
});

export const currentUser = query({
  args: {
    token: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.user.safeGet(ctx, args.token);
  },
});

export const updateProfile = mutation({
  args: {
    token: v.optional(v.string()),
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    username: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.updateProfile(ctx, args);
  },
});


export const getOAuthUrl = mutation({
  args: {
    providerId: v.string(),
    callbackUrl: v.optional(v.string()),
    returnTarget: v.optional(v.string()),
    proxyMode: v.optional(v.union(v.literal("direct"), v.literal("broker"))),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.getOAuthUrl(ctx, args.providerId, {
      callbackUrl: args.callbackUrl,
      returnTarget: args.returnTarget,
      proxyMode: args.proxyMode,
      redirectTo: args.redirectTo,
      errorRedirectTo: args.errorRedirectTo,
      redirectUrl: args.redirectUrl,
    });
  },
});

export const handleOAuthCallback = action({
  args: {
    providerId: v.string(),
    code: v.string(),
    state: v.string(),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.handleCallback(ctx, args);
  },
});

export const handleOAuthProxyCallback = action({
  args: {
    providerId: v.string(),
    code: v.string(),
    state: v.string(),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.handleProxyCallback(ctx, args);
  },
});

export const exchangeOAuthProxyCode = action({
  args: {
    code: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.exchangeOAuthProxyCode(ctx, args);
  },
});
