// @generated by convex-zen generate. DO NOT EDIT.
import { createConvexZenClient } from "convex-zen";
import { makeFunctionReference, type FunctionReference } from "convex/server";
import zenConfig from "../../zen.config";

function componentFn<TKind extends "query" | "mutation" | "action">(
  path: string
): FunctionReference<TKind, "public" | "internal"> {
  return makeFunctionReference(path);
}

export const auth = createConvexZenClient(
  {},
  zenConfig,
  {
    runtimeKind: "component",
    coreRefs: {
      gateway: {
    signUp: componentFn<"mutation">("core/gateway:signUp"),
    signIn: componentFn<"mutation">("core/gateway:signIn"),
    updateProfile: componentFn<"mutation">("core/gateway:updateProfile"),
    verifyEmail: componentFn<"mutation">("core/gateway:verifyEmail"),
    requestPasswordReset: componentFn<"mutation">("core/gateway:requestPasswordReset"),
    resetPassword: componentFn<"mutation">("core/gateway:resetPassword"),
    validateSession: componentFn<"mutation">("core/gateway:validateSession"),
    getCurrentUser: componentFn<"query">("core/gateway:getCurrentUser"),
    getUserById: componentFn<"query">("core/gateway:getUserById"),
    invalidateSession: componentFn<"mutation">("core/gateway:invalidateSession"),
    invalidateAllSessions: componentFn<"mutation">("core/gateway:invalidateAllSessions"),
    getAuthorizationUrl: componentFn<"mutation">("core/gateway:getAuthorizationUrl"),
    resolveOAuthCallbackData: componentFn<"action">("core/gateway:resolveOAuthCallbackData"),
    inspectOAuthIdentityCandidate: componentFn<"query">("core/gateway:inspectOAuthIdentityCandidate"),
    validateOAuthUsernameCandidate: componentFn<"query">("core/gateway:validateOAuthUsernameCandidate"),
    getOAuthUserSnapshot: componentFn<"query">("core/gateway:getOAuthUserSnapshot"),
    applyOAuthSignInPatch: componentFn<"mutation">("core/gateway:applyOAuthSignInPatch"),
    createOAuthProxyHandoff: componentFn<"action">("core/gateway:createOAuthProxyHandoff"),
    finalizeOAuthIdentity: componentFn<"mutation">("core/gateway:finalizeOAuthIdentity"),
    assertUserNotBanned: componentFn<"mutation">("core/gateway:assertUserNotBanned"),
    createSessionForOAuth: componentFn<"mutation">("core/gateway:createSessionForOAuth"),
    exchangeProxyCode: componentFn<"action">("core/gateway:exchangeProxyCode"),
    handleCallback: componentFn<"action">("core/gateway:handleCallback"),
      } as Record<string, unknown>,
      removeUser: componentFn<"mutation">("core/users:remove"),
    },
  }
);
