// @generated by convex-zen generate. DO NOT EDIT.
import { defineSchema } from "convex/server";
import { createCoreSchemaTables } from "convex-zen/component/core-schema-definition";


export default defineSchema({
  ...createCoreSchemaTables(),

});
