/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultRouteRouteImport } from './routes/_default/route'
import { Route as DefaultIndexRouteImport } from './routes/_default/index'
import { Route as DefaultSettingsRouteImport } from './routes/_default/settings'
import { Route as DefaultWnbaIndexRouteImport } from './routes/_default/wnba/index'
import { Route as DefaultNbaIndexRouteImport } from './routes/_default/nba/index'
import { Route as DefaultGleagueIndexRouteImport } from './routes/_default/gleague/index'
import { Route as DefaultAdminIndexRouteImport } from './routes/_default/admin/index'
import { Route as DefaultAboutIndexRouteImport } from './routes/_default/about/index'
import { Route as ApiHeadshotPlayerIdRouteImport } from './routes/api/headshot/$playerId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DefaultWnbaStandingsRouteImport } from './routes/_default/wnba/standings'
import { Route as DefaultWnbaScoresRouteImport } from './routes/_default/wnba/scores'
import { Route as DefaultProfileUsernameRouteImport } from './routes/_default/profile/$username'
import { Route as DefaultNbaStandingsRouteImport } from './routes/_default/nba/standings'
import { Route as DefaultNbaScoresRouteImport } from './routes/_default/nba/scores'
import { Route as DefaultGleagueStandingsRouteImport } from './routes/_default/gleague/standings'
import { Route as DefaultGleagueScoresRouteImport } from './routes/_default/gleague/scores'
import { Route as DefaultAuthSignInRouteImport } from './routes/_default/auth/sign-in'
import { Route as ApiWnbaLogoIdRouteImport } from './routes/api/wnba/logo/$id'
import { Route as ApiNbaLogoIdRouteImport } from './routes/api/nba/logo/$id'
import { Route as ApiGleagueLogoIdRouteImport } from './routes/api/gleague/logo/$id'
import { Route as DefaultWnbaTeamTeamIdRouteImport } from './routes/_default/wnba/team/$teamId'
import { Route as DefaultWnbaGameGameIdRouteImport } from './routes/_default/wnba/game/$gameId'
import { Route as DefaultNbaTeamTeamIdRouteImport } from './routes/_default/nba/team/$teamId'
import { Route as DefaultNbaGameGameIdRouteImport } from './routes/_default/nba/game/$gameId'
import { Route as DefaultGleagueTeamTeamIdRouteImport } from './routes/_default/gleague/team/$teamId'
import { Route as DefaultGleagueGameGameIdRouteImport } from './routes/_default/gleague/game/$gameId'

const DefaultRouteRoute = DefaultRouteRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultSettingsRoute = DefaultSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultWnbaIndexRoute = DefaultWnbaIndexRouteImport.update({
  id: '/wnba/',
  path: '/wnba/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultNbaIndexRoute = DefaultNbaIndexRouteImport.update({
  id: '/nba/',
  path: '/nba/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultGleagueIndexRoute = DefaultGleagueIndexRouteImport.update({
  id: '/gleague/',
  path: '/gleague/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultAdminIndexRoute = DefaultAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultAboutIndexRoute = DefaultAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const ApiHeadshotPlayerIdRoute = ApiHeadshotPlayerIdRouteImport.update({
  id: '/api/headshot/$playerId',
  path: '/api/headshot/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultWnbaStandingsRoute = DefaultWnbaStandingsRouteImport.update({
  id: '/wnba/standings',
  path: '/wnba/standings',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultWnbaScoresRoute = DefaultWnbaScoresRouteImport.update({
  id: '/wnba/scores',
  path: '/wnba/scores',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultProfileUsernameRoute = DefaultProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultNbaStandingsRoute = DefaultNbaStandingsRouteImport.update({
  id: '/nba/standings',
  path: '/nba/standings',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultNbaScoresRoute = DefaultNbaScoresRouteImport.update({
  id: '/nba/scores',
  path: '/nba/scores',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultGleagueStandingsRoute = DefaultGleagueStandingsRouteImport.update({
  id: '/gleague/standings',
  path: '/gleague/standings',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultGleagueScoresRoute = DefaultGleagueScoresRouteImport.update({
  id: '/gleague/scores',
  path: '/gleague/scores',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultAuthSignInRoute = DefaultAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const ApiWnbaLogoIdRoute = ApiWnbaLogoIdRouteImport.update({
  id: '/api/wnba/logo/$id',
  path: '/api/wnba/logo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNbaLogoIdRoute = ApiNbaLogoIdRouteImport.update({
  id: '/api/nba/logo/$id',
  path: '/api/nba/logo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGleagueLogoIdRoute = ApiGleagueLogoIdRouteImport.update({
  id: '/api/gleague/logo/$id',
  path: '/api/gleague/logo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultWnbaTeamTeamIdRoute = DefaultWnbaTeamTeamIdRouteImport.update({
  id: '/wnba/team/$teamId',
  path: '/wnba/team/$teamId',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultWnbaGameGameIdRoute = DefaultWnbaGameGameIdRouteImport.update({
  id: '/wnba/game/$gameId',
  path: '/wnba/game/$gameId',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultNbaTeamTeamIdRoute = DefaultNbaTeamTeamIdRouteImport.update({
  id: '/nba/team/$teamId',
  path: '/nba/team/$teamId',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultNbaGameGameIdRoute = DefaultNbaGameGameIdRouteImport.update({
  id: '/nba/game/$gameId',
  path: '/nba/game/$gameId',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const DefaultGleagueTeamTeamIdRoute =
  DefaultGleagueTeamTeamIdRouteImport.update({
    id: '/gleague/team/$teamId',
    path: '/gleague/team/$teamId',
    getParentRoute: () => DefaultRouteRoute,
  } as any)
const DefaultGleagueGameGameIdRoute =
  DefaultGleagueGameGameIdRouteImport.update({
    id: '/gleague/game/$gameId',
    path: '/gleague/game/$gameId',
    getParentRoute: () => DefaultRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute
  '/settings': typeof DefaultSettingsRoute
  '/auth/sign-in': typeof DefaultAuthSignInRoute
  '/gleague/scores': typeof DefaultGleagueScoresRoute
  '/gleague/standings': typeof DefaultGleagueStandingsRoute
  '/nba/scores': typeof DefaultNbaScoresRoute
  '/nba/standings': typeof DefaultNbaStandingsRoute
  '/profile/$username': typeof DefaultProfileUsernameRoute
  '/wnba/scores': typeof DefaultWnbaScoresRoute
  '/wnba/standings': typeof DefaultWnbaStandingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/headshot/$playerId': typeof ApiHeadshotPlayerIdRoute
  '/about/': typeof DefaultAboutIndexRoute
  '/admin/': typeof DefaultAdminIndexRoute
  '/gleague/': typeof DefaultGleagueIndexRoute
  '/nba/': typeof DefaultNbaIndexRoute
  '/wnba/': typeof DefaultWnbaIndexRoute
  '/gleague/game/$gameId': typeof DefaultGleagueGameGameIdRoute
  '/gleague/team/$teamId': typeof DefaultGleagueTeamTeamIdRoute
  '/nba/game/$gameId': typeof DefaultNbaGameGameIdRoute
  '/nba/team/$teamId': typeof DefaultNbaTeamTeamIdRoute
  '/wnba/game/$gameId': typeof DefaultWnbaGameGameIdRoute
  '/wnba/team/$teamId': typeof DefaultWnbaTeamTeamIdRoute
  '/api/gleague/logo/$id': typeof ApiGleagueLogoIdRoute
  '/api/nba/logo/$id': typeof ApiNbaLogoIdRoute
  '/api/wnba/logo/$id': typeof ApiWnbaLogoIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof DefaultSettingsRoute
  '/': typeof DefaultIndexRoute
  '/auth/sign-in': typeof DefaultAuthSignInRoute
  '/gleague/scores': typeof DefaultGleagueScoresRoute
  '/gleague/standings': typeof DefaultGleagueStandingsRoute
  '/nba/scores': typeof DefaultNbaScoresRoute
  '/nba/standings': typeof DefaultNbaStandingsRoute
  '/profile/$username': typeof DefaultProfileUsernameRoute
  '/wnba/scores': typeof DefaultWnbaScoresRoute
  '/wnba/standings': typeof DefaultWnbaStandingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/headshot/$playerId': typeof ApiHeadshotPlayerIdRoute
  '/about': typeof DefaultAboutIndexRoute
  '/admin': typeof DefaultAdminIndexRoute
  '/gleague': typeof DefaultGleagueIndexRoute
  '/nba': typeof DefaultNbaIndexRoute
  '/wnba': typeof DefaultWnbaIndexRoute
  '/gleague/game/$gameId': typeof DefaultGleagueGameGameIdRoute
  '/gleague/team/$teamId': typeof DefaultGleagueTeamTeamIdRoute
  '/nba/game/$gameId': typeof DefaultNbaGameGameIdRoute
  '/nba/team/$teamId': typeof DefaultNbaTeamTeamIdRoute
  '/wnba/game/$gameId': typeof DefaultWnbaGameGameIdRoute
  '/wnba/team/$teamId': typeof DefaultWnbaTeamTeamIdRoute
  '/api/gleague/logo/$id': typeof ApiGleagueLogoIdRoute
  '/api/nba/logo/$id': typeof ApiNbaLogoIdRoute
  '/api/wnba/logo/$id': typeof ApiWnbaLogoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_default': typeof DefaultRouteRouteWithChildren
  '/_default/settings': typeof DefaultSettingsRoute
  '/_default/': typeof DefaultIndexRoute
  '/_default/auth/sign-in': typeof DefaultAuthSignInRoute
  '/_default/gleague/scores': typeof DefaultGleagueScoresRoute
  '/_default/gleague/standings': typeof DefaultGleagueStandingsRoute
  '/_default/nba/scores': typeof DefaultNbaScoresRoute
  '/_default/nba/standings': typeof DefaultNbaStandingsRoute
  '/_default/profile/$username': typeof DefaultProfileUsernameRoute
  '/_default/wnba/scores': typeof DefaultWnbaScoresRoute
  '/_default/wnba/standings': typeof DefaultWnbaStandingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/headshot/$playerId': typeof ApiHeadshotPlayerIdRoute
  '/_default/about/': typeof DefaultAboutIndexRoute
  '/_default/admin/': typeof DefaultAdminIndexRoute
  '/_default/gleague/': typeof DefaultGleagueIndexRoute
  '/_default/nba/': typeof DefaultNbaIndexRoute
  '/_default/wnba/': typeof DefaultWnbaIndexRoute
  '/_default/gleague/game/$gameId': typeof DefaultGleagueGameGameIdRoute
  '/_default/gleague/team/$teamId': typeof DefaultGleagueTeamTeamIdRoute
  '/_default/nba/game/$gameId': typeof DefaultNbaGameGameIdRoute
  '/_default/nba/team/$teamId': typeof DefaultNbaTeamTeamIdRoute
  '/_default/wnba/game/$gameId': typeof DefaultWnbaGameGameIdRoute
  '/_default/wnba/team/$teamId': typeof DefaultWnbaTeamTeamIdRoute
  '/api/gleague/logo/$id': typeof ApiGleagueLogoIdRoute
  '/api/nba/logo/$id': typeof ApiNbaLogoIdRoute
  '/api/wnba/logo/$id': typeof ApiWnbaLogoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/sign-in'
    | '/gleague/scores'
    | '/gleague/standings'
    | '/nba/scores'
    | '/nba/standings'
    | '/profile/$username'
    | '/wnba/scores'
    | '/wnba/standings'
    | '/api/auth/$'
    | '/api/headshot/$playerId'
    | '/about/'
    | '/admin/'
    | '/gleague/'
    | '/nba/'
    | '/wnba/'
    | '/gleague/game/$gameId'
    | '/gleague/team/$teamId'
    | '/nba/game/$gameId'
    | '/nba/team/$teamId'
    | '/wnba/game/$gameId'
    | '/wnba/team/$teamId'
    | '/api/gleague/logo/$id'
    | '/api/nba/logo/$id'
    | '/api/wnba/logo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/auth/sign-in'
    | '/gleague/scores'
    | '/gleague/standings'
    | '/nba/scores'
    | '/nba/standings'
    | '/profile/$username'
    | '/wnba/scores'
    | '/wnba/standings'
    | '/api/auth/$'
    | '/api/headshot/$playerId'
    | '/about'
    | '/admin'
    | '/gleague'
    | '/nba'
    | '/wnba'
    | '/gleague/game/$gameId'
    | '/gleague/team/$teamId'
    | '/nba/game/$gameId'
    | '/nba/team/$teamId'
    | '/wnba/game/$gameId'
    | '/wnba/team/$teamId'
    | '/api/gleague/logo/$id'
    | '/api/nba/logo/$id'
    | '/api/wnba/logo/$id'
  id:
    | '__root__'
    | '/_default'
    | '/_default/settings'
    | '/_default/'
    | '/_default/auth/sign-in'
    | '/_default/gleague/scores'
    | '/_default/gleague/standings'
    | '/_default/nba/scores'
    | '/_default/nba/standings'
    | '/_default/profile/$username'
    | '/_default/wnba/scores'
    | '/_default/wnba/standings'
    | '/api/auth/$'
    | '/api/headshot/$playerId'
    | '/_default/about/'
    | '/_default/admin/'
    | '/_default/gleague/'
    | '/_default/nba/'
    | '/_default/wnba/'
    | '/_default/gleague/game/$gameId'
    | '/_default/gleague/team/$teamId'
    | '/_default/nba/game/$gameId'
    | '/_default/nba/team/$teamId'
    | '/_default/wnba/game/$gameId'
    | '/_default/wnba/team/$teamId'
    | '/api/gleague/logo/$id'
    | '/api/nba/logo/$id'
    | '/api/wnba/logo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DefaultRouteRoute: typeof DefaultRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHeadshotPlayerIdRoute: typeof ApiHeadshotPlayerIdRoute
  ApiGleagueLogoIdRoute: typeof ApiGleagueLogoIdRoute
  ApiNbaLogoIdRoute: typeof ApiNbaLogoIdRoute
  ApiWnbaLogoIdRoute: typeof ApiWnbaLogoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/settings': {
      id: '/_default/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DefaultSettingsRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/wnba/': {
      id: '/_default/wnba/'
      path: '/wnba'
      fullPath: '/wnba/'
      preLoaderRoute: typeof DefaultWnbaIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/nba/': {
      id: '/_default/nba/'
      path: '/nba'
      fullPath: '/nba/'
      preLoaderRoute: typeof DefaultNbaIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/gleague/': {
      id: '/_default/gleague/'
      path: '/gleague'
      fullPath: '/gleague/'
      preLoaderRoute: typeof DefaultGleagueIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/admin/': {
      id: '/_default/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof DefaultAdminIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/about/': {
      id: '/_default/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof DefaultAboutIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/api/headshot/$playerId': {
      id: '/api/headshot/$playerId'
      path: '/api/headshot/$playerId'
      fullPath: '/api/headshot/$playerId'
      preLoaderRoute: typeof ApiHeadshotPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/wnba/standings': {
      id: '/_default/wnba/standings'
      path: '/wnba/standings'
      fullPath: '/wnba/standings'
      preLoaderRoute: typeof DefaultWnbaStandingsRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/wnba/scores': {
      id: '/_default/wnba/scores'
      path: '/wnba/scores'
      fullPath: '/wnba/scores'
      preLoaderRoute: typeof DefaultWnbaScoresRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/profile/$username': {
      id: '/_default/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof DefaultProfileUsernameRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/nba/standings': {
      id: '/_default/nba/standings'
      path: '/nba/standings'
      fullPath: '/nba/standings'
      preLoaderRoute: typeof DefaultNbaStandingsRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/nba/scores': {
      id: '/_default/nba/scores'
      path: '/nba/scores'
      fullPath: '/nba/scores'
      preLoaderRoute: typeof DefaultNbaScoresRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/gleague/standings': {
      id: '/_default/gleague/standings'
      path: '/gleague/standings'
      fullPath: '/gleague/standings'
      preLoaderRoute: typeof DefaultGleagueStandingsRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/gleague/scores': {
      id: '/_default/gleague/scores'
      path: '/gleague/scores'
      fullPath: '/gleague/scores'
      preLoaderRoute: typeof DefaultGleagueScoresRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/auth/sign-in': {
      id: '/_default/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof DefaultAuthSignInRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/api/wnba/logo/$id': {
      id: '/api/wnba/logo/$id'
      path: '/api/wnba/logo/$id'
      fullPath: '/api/wnba/logo/$id'
      preLoaderRoute: typeof ApiWnbaLogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nba/logo/$id': {
      id: '/api/nba/logo/$id'
      path: '/api/nba/logo/$id'
      fullPath: '/api/nba/logo/$id'
      preLoaderRoute: typeof ApiNbaLogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gleague/logo/$id': {
      id: '/api/gleague/logo/$id'
      path: '/api/gleague/logo/$id'
      fullPath: '/api/gleague/logo/$id'
      preLoaderRoute: typeof ApiGleagueLogoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default/wnba/team/$teamId': {
      id: '/_default/wnba/team/$teamId'
      path: '/wnba/team/$teamId'
      fullPath: '/wnba/team/$teamId'
      preLoaderRoute: typeof DefaultWnbaTeamTeamIdRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/wnba/game/$gameId': {
      id: '/_default/wnba/game/$gameId'
      path: '/wnba/game/$gameId'
      fullPath: '/wnba/game/$gameId'
      preLoaderRoute: typeof DefaultWnbaGameGameIdRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/nba/team/$teamId': {
      id: '/_default/nba/team/$teamId'
      path: '/nba/team/$teamId'
      fullPath: '/nba/team/$teamId'
      preLoaderRoute: typeof DefaultNbaTeamTeamIdRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/nba/game/$gameId': {
      id: '/_default/nba/game/$gameId'
      path: '/nba/game/$gameId'
      fullPath: '/nba/game/$gameId'
      preLoaderRoute: typeof DefaultNbaGameGameIdRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/gleague/team/$teamId': {
      id: '/_default/gleague/team/$teamId'
      path: '/gleague/team/$teamId'
      fullPath: '/gleague/team/$teamId'
      preLoaderRoute: typeof DefaultGleagueTeamTeamIdRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_default/gleague/game/$gameId': {
      id: '/_default/gleague/game/$gameId'
      path: '/gleague/game/$gameId'
      fullPath: '/gleague/game/$gameId'
      preLoaderRoute: typeof DefaultGleagueGameGameIdRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
  }
}

interface DefaultRouteRouteChildren {
  DefaultSettingsRoute: typeof DefaultSettingsRoute
  DefaultIndexRoute: typeof DefaultIndexRoute
  DefaultAuthSignInRoute: typeof DefaultAuthSignInRoute
  DefaultGleagueScoresRoute: typeof DefaultGleagueScoresRoute
  DefaultGleagueStandingsRoute: typeof DefaultGleagueStandingsRoute
  DefaultNbaScoresRoute: typeof DefaultNbaScoresRoute
  DefaultNbaStandingsRoute: typeof DefaultNbaStandingsRoute
  DefaultProfileUsernameRoute: typeof DefaultProfileUsernameRoute
  DefaultWnbaScoresRoute: typeof DefaultWnbaScoresRoute
  DefaultWnbaStandingsRoute: typeof DefaultWnbaStandingsRoute
  DefaultAboutIndexRoute: typeof DefaultAboutIndexRoute
  DefaultAdminIndexRoute: typeof DefaultAdminIndexRoute
  DefaultGleagueIndexRoute: typeof DefaultGleagueIndexRoute
  DefaultNbaIndexRoute: typeof DefaultNbaIndexRoute
  DefaultWnbaIndexRoute: typeof DefaultWnbaIndexRoute
  DefaultGleagueGameGameIdRoute: typeof DefaultGleagueGameGameIdRoute
  DefaultGleagueTeamTeamIdRoute: typeof DefaultGleagueTeamTeamIdRoute
  DefaultNbaGameGameIdRoute: typeof DefaultNbaGameGameIdRoute
  DefaultNbaTeamTeamIdRoute: typeof DefaultNbaTeamTeamIdRoute
  DefaultWnbaGameGameIdRoute: typeof DefaultWnbaGameGameIdRoute
  DefaultWnbaTeamTeamIdRoute: typeof DefaultWnbaTeamTeamIdRoute
}

const DefaultRouteRouteChildren: DefaultRouteRouteChildren = {
  DefaultSettingsRoute: DefaultSettingsRoute,
  DefaultIndexRoute: DefaultIndexRoute,
  DefaultAuthSignInRoute: DefaultAuthSignInRoute,
  DefaultGleagueScoresRoute: DefaultGleagueScoresRoute,
  DefaultGleagueStandingsRoute: DefaultGleagueStandingsRoute,
  DefaultNbaScoresRoute: DefaultNbaScoresRoute,
  DefaultNbaStandingsRoute: DefaultNbaStandingsRoute,
  DefaultProfileUsernameRoute: DefaultProfileUsernameRoute,
  DefaultWnbaScoresRoute: DefaultWnbaScoresRoute,
  DefaultWnbaStandingsRoute: DefaultWnbaStandingsRoute,
  DefaultAboutIndexRoute: DefaultAboutIndexRoute,
  DefaultAdminIndexRoute: DefaultAdminIndexRoute,
  DefaultGleagueIndexRoute: DefaultGleagueIndexRoute,
  DefaultNbaIndexRoute: DefaultNbaIndexRoute,
  DefaultWnbaIndexRoute: DefaultWnbaIndexRoute,
  DefaultGleagueGameGameIdRoute: DefaultGleagueGameGameIdRoute,
  DefaultGleagueTeamTeamIdRoute: DefaultGleagueTeamTeamIdRoute,
  DefaultNbaGameGameIdRoute: DefaultNbaGameGameIdRoute,
  DefaultNbaTeamTeamIdRoute: DefaultNbaTeamTeamIdRoute,
  DefaultWnbaGameGameIdRoute: DefaultWnbaGameGameIdRoute,
  DefaultWnbaTeamTeamIdRoute: DefaultWnbaTeamTeamIdRoute,
}

const DefaultRouteRouteWithChildren = DefaultRouteRoute._addFileChildren(
  DefaultRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DefaultRouteRoute: DefaultRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHeadshotPlayerIdRoute: ApiHeadshotPlayerIdRoute,
  ApiGleagueLogoIdRoute: ApiGleagueLogoIdRoute,
  ApiNbaLogoIdRoute: ApiNbaLogoIdRoute,
  ApiWnbaLogoIdRoute: ApiWnbaLogoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
