/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NflIndexRouteImport } from './routes/nfl/index'
import { Route as NbaIndexRouteImport } from './routes/nba/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NflIndexRoute = NflIndexRouteImport.update({
  id: '/nfl/',
  path: '/nfl/',
  getParentRoute: () => rootRouteImport,
} as any)
const NbaIndexRoute = NbaIndexRouteImport.update({
  id: '/nba/',
  path: '/nba/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nba/': typeof NbaIndexRoute
  '/nfl/': typeof NflIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nba': typeof NbaIndexRoute
  '/nfl': typeof NflIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nba/': typeof NbaIndexRoute
  '/nfl/': typeof NflIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nba/' | '/nfl/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nba' | '/nfl'
  id: '__root__' | '/' | '/nba/' | '/nfl/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NbaIndexRoute: typeof NbaIndexRoute
  NflIndexRoute: typeof NflIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfl/': {
      id: '/nfl/'
      path: '/nfl'
      fullPath: '/nfl/'
      preLoaderRoute: typeof NflIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nba/': {
      id: '/nba/'
      path: '/nba'
      fullPath: '/nba/'
      preLoaderRoute: typeof NbaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NbaIndexRoute: NbaIndexRoute,
  NflIndexRoute: NflIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
