import type { TeamDefinition } from "../types";

export const NBA_TEAMS: TeamDefinition[] = [
	{
		name: "Hawks",
		city: "Atlanta",
		fullName: "Atlanta Hawks",
		abbreviation: "ATL",
		logoSlug: "atl",
		colors: {
			brand: { primary: "E03A3E", secondary: "C1D32F" },
			display: { dark: "E03A3E", light: "E03A3E" },
		},
		espn: { id: "1", slug: "atl" },
	},
	{
		name: "Celtics",
		city: "Boston",
		fullName: "Boston Celtics",
		abbreviation: "BOS",
		logoSlug: "bos",
		colors: {
			brand: { primary: "007A33", secondary: "BA9653" },
			display: { dark: "BA9653", light: "007A33" },
		},
		espn: { id: "2", slug: "bos" },
	},
	{
		name: "Nets",
		city: "Brooklyn",
		fullName: "Brooklyn Nets",
		abbreviation: "BKN",
		logoSlug: "bkn",
		colors: {
			brand: { primary: "000000", secondary: "FFFFFF" },
			display: { dark: "FFFFFF", light: "000000" },
		},
		espn: { id: "17", slug: "bkn" },
	},
	{
		name: "Hornets",
		city: "Charlotte",
		fullName: "Charlotte Hornets",
		abbreviation: "CHA",
		logoSlug: "cha",
		colors: {
			brand: { primary: "1D1160", secondary: "00788C" },
			display: { dark: "00788C", light: "1D1160" },
		},
		espn: { id: "30", slug: "cha" },
	},
	{
		name: "Bulls",
		city: "Chicago",
		fullName: "Chicago Bulls",
		abbreviation: "CHI",
		logoSlug: "chi",
		colors: {
			brand: { primary: "CE1141", secondary: "000000" },
			display: { dark: "CE1141", light: "CE1141" },
		},
		espn: { id: "4", slug: "chi" },
	},
	{
		name: "Cavaliers",
		city: "Cleveland",
		fullName: "Cleveland Cavaliers",
		abbreviation: "CLE",
		logoSlug: "cle",
		colors: {
			brand: { primary: "860038", secondary: "FDBB30" },
			display: { dark: "FDBB30", light: "860038" },
		},
		espn: { id: "5", slug: "cle" },
	},
	{
		name: "Mavericks",
		city: "Dallas",
		fullName: "Dallas Mavericks",
		abbreviation: "DAL",
		logoSlug: "dal",
		colors: {
			brand: { primary: "00538C", secondary: "002B5E" },
			display: { dark: "00538C", light: "00538C" },
		},
		espn: { id: "6", slug: "dal" },
	},
	{
		name: "Nuggets",
		city: "Denver",
		fullName: "Denver Nuggets",
		abbreviation: "DEN",
		logoSlug: "den",
		colors: {
			brand: { primary: "0E2240", secondary: "FEC524" },
			display: { dark: "FEC524", light: "0E2240" },
		},
		espn: { id: "7", slug: "den" },
	},
	{
		name: "Pistons",
		city: "Detroit",
		fullName: "Detroit Pistons",
		abbreviation: "DET",
		logoSlug: "det",
		colors: {
			brand: { primary: "C8102E", secondary: "1D42BA" },
			display: { dark: "C8102E", light: "1D42BA" },
		},
		espn: { id: "8", slug: "det" },
	},
	{
		name: "Warriors",
		city: "Golden State",
		fullName: "Golden State Warriors",
		abbreviation: "GSW",
		logoSlug: "gs",
		colors: {
			brand: { primary: "1D428A", secondary: "FFC72C" },
			display: { dark: "FFC72C", light: "1D428A" },
		},
		espn: { id: "9", slug: "gs" },
	},
	{
		name: "Rockets",
		city: "Houston",
		fullName: "Houston Rockets",
		abbreviation: "HOU",
		logoSlug: "hou",
		colors: {
			brand: { primary: "CE1141", secondary: "000000" },
			display: { dark: "CE1141", light: "CE1141" },
		},
		espn: { id: "10", slug: "hou" },
	},
	{
		name: "Pacers",
		city: "Indiana",
		fullName: "Indiana Pacers",
		abbreviation: "IND",
		logoSlug: "ind",
		colors: {
			brand: { primary: "002D62", secondary: "FDBB30" },
			display: { dark: "FDBB30", light: "002D62" },
		},
		espn: { id: "11", slug: "ind" },
	},
	{
		name: "Clippers",
		city: "Los Angeles",
		fullName: "Los Angeles Clippers",
		abbreviation: "LAC",
		logoSlug: "lac",
		colors: {
			brand: { primary: "C8102E", secondary: "1D428A" },
			display: { dark: "C8102E", light: "1D428A" },
		},
		espn: { id: "12", slug: "lac" },
	},
	{
		name: "Lakers",
		city: "Los Angeles",
		fullName: "Los Angeles Lakers",
		abbreviation: "LAL",
		logoSlug: "lal",
		colors: {
			brand: { primary: "552583", secondary: "FDB927" },
			display: { dark: "FDB927", light: "552583" },
		},
		espn: { id: "13", slug: "lal" },
	},
	{
		name: "Grizzlies",
		city: "Memphis",
		fullName: "Memphis Grizzlies",
		abbreviation: "MEM",
		logoSlug: "mem",
		colors: {
			brand: { primary: "5D76A9", secondary: "12173F" },
			display: { dark: "5D76A9", light: "12173F" },
		},
		espn: { id: "29", slug: "mem" },
	},
	{
		name: "Heat",
		city: "Miami",
		fullName: "Miami Heat",
		abbreviation: "MIA",
		logoSlug: "mia",
		colors: {
			brand: { primary: "98002E", secondary: "F9A01B" },
			display: { dark: "F9A01B", light: "98002E" },
		},
		espn: { id: "14", slug: "mia" },
	},
	{
		name: "Bucks",
		city: "Milwaukee",
		fullName: "Milwaukee Bucks",
		abbreviation: "MIL",
		logoSlug: "mil",
		colors: {
			brand: { primary: "00471B", secondary: "EEE1C6" },
			display: { dark: "EEE1C6", light: "00471B" },
		},
		espn: { id: "15", slug: "mil" },
	},
	{
		name: "Timberwolves",
		city: "Minnesota",
		fullName: "Minnesota Timberwolves",
		abbreviation: "MIN",
		logoSlug: "min",
		colors: {
			brand: { primary: "0C2340", secondary: "236192" },
			display: { dark: "236192", light: "0C2340" },
		},
		espn: { id: "16", slug: "min" },
	},
	{
		name: "Pelicans",
		city: "New Orleans",
		fullName: "New Orleans Pelicans",
		abbreviation: "NOP",
		logoSlug: "no",
		colors: {
			brand: { primary: "0C2340", secondary: "C8102E" },
			display: { dark: "C8102E", light: "0C2340" },
		},
		espn: { id: "3", slug: "no" },
	},
	{
		name: "Knicks",
		city: "New York",
		fullName: "New York Knicks",
		abbreviation: "NYK",
		logoSlug: "ny",
		colors: {
			brand: { primary: "006BB6", secondary: "F58426" },
			display: { dark: "F58426", light: "006BB6" },
		},
		espn: { id: "18", slug: "ny" },
	},
	{
		name: "Thunder",
		city: "Oklahoma City",
		fullName: "Oklahoma City Thunder",
		abbreviation: "OKC",
		logoSlug: "okc",
		colors: {
			brand: { primary: "007AC1", secondary: "EF3B24" },
			display: { dark: "007AC1", light: "007AC1" },
		},
		espn: { id: "25", slug: "okc" },
	},
	{
		name: "Magic",
		city: "Orlando",
		fullName: "Orlando Magic",
		abbreviation: "ORL",
		logoSlug: "orl",
		colors: {
			brand: { primary: "0077C0", secondary: "C4CED4" },
			display: { dark: "0077C0", light: "0077C0" },
		},
		espn: { id: "19", slug: "orl" },
	},
	{
		name: "76ers",
		city: "Philadelphia",
		fullName: "Philadelphia 76ers",
		abbreviation: "PHI",
		logoSlug: "phi",
		colors: {
			brand: { primary: "006BB6", secondary: "ED174C" },
			display: { dark: "ED174C", light: "006BB6" },
		},
		espn: { id: "20", slug: "phi" },
	},
	{
		name: "Suns",
		city: "Phoenix",
		fullName: "Phoenix Suns",
		abbreviation: "PHX",
		logoSlug: "phx",
		colors: {
			brand: { primary: "1D1160", secondary: "E56020" },
			display: { dark: "E56020", light: "1D1160" },
		},
		espn: { id: "21", slug: "phx" },
	},
	{
		name: "Trail Blazers",
		city: "Portland",
		fullName: "Portland Trail Blazers",
		abbreviation: "POR",
		logoSlug: "por",
		colors: {
			brand: { primary: "E03A3E", secondary: "000000" },
			display: { dark: "E03A3E", light: "E03A3E" },
		},
		espn: { id: "22", slug: "por" },
	},
	{
		name: "Kings",
		city: "Sacramento",
		fullName: "Sacramento Kings",
		abbreviation: "SAC",
		logoSlug: "sac",
		colors: {
			brand: { primary: "5A2D81", secondary: "63727A" },
			display: { dark: "5A2D81", light: "5A2D81" },
		},
		espn: { id: "23", slug: "sac" },
	},
	{
		name: "Spurs",
		city: "San Antonio",
		fullName: "San Antonio Spurs",
		abbreviation: "SAS",
		logoSlug: "sa",
		colors: {
			brand: { primary: "C4CED4", secondary: "000000" },
			display: { dark: "C4CED4", light: "000000" },
		},
		espn: { id: "24", slug: "sa" },
	},
	{
		name: "Raptors",
		city: "Toronto",
		fullName: "Toronto Raptors",
		abbreviation: "TOR",
		logoSlug: "tor",
		colors: {
			brand: { primary: "CE1141", secondary: "000000" },
			display: { dark: "CE1141", light: "CE1141" },
		},
		espn: { id: "28", slug: "tor" },
	},
	{
		name: "Jazz",
		city: "Utah",
		fullName: "Utah Jazz",
		abbreviation: "UTA",
		logoSlug: "utah",
		colors: {
			brand: { primary: "002B5C", secondary: "00471B" },
			display: { dark: "F9A01B", light: "002B5C" },
		},
		espn: { id: "26", slug: "utah" },
	},
	{
		name: "Wizards",
		city: "Washington",
		fullName: "Washington Wizards",
		abbreviation: "WAS",
		logoSlug: "wsh",
		colors: {
			brand: { primary: "002B5C", secondary: "E31837" },
			display: { dark: "E31837", light: "002B5C" },
		},
		espn: { id: "27", slug: "wsh" },
	},
];
